### ISSUE TITLE
Tried to use a NULL entity! [CLIENT]

### ISSUE THREAD

**Issue by Flapchik** [actuallyNothing/tttstopwatch#2]
`[tttstopwatch-main] addons/tttstopwatch-main/gamemodes/terrortown/entities/entities/ttt_stopwatch/cl_init.lua:69: Tried to use a NULL entity!
  1. StopSound - [C]:-1
   2. finish_stopwatch - addons/tttstopwatch-main/gamemodes/terrortown/entities/entities/ttt_stopwatch/cl_init.lua:69
    3. func - addons/tttstopwatch-main/gamemodes/terrortown/entities/entities/ttt_stopwatch/cl_init.lua:75
     4. unknown - lua/includes/extensions/net.lua:33`
I don't know how this error happens, sry :(

**Comment by velrmilion** [comment]
Hello, do you remember any details on the particular situation this error ocurred, or is there anything of note about the moment it showed up?

**Comment by Flapchik** [comment]
![image](https://user-images.githubusercontent.com/58729268/180383165-330b863d-866a-4ef0-89a6-c00997e5439b.png)
Client connected!

**Comment by velrmilion** [comment]
Thanks, that cleared it up (the bug occurs when the round ends while someone is joining the server). Latest commit should fix it, please tell me if this error pops up again!
